version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  eslint:
    enabled: true
  stylelint:
    enabled: true
exclude_patterns:
  - "**/node_modules/"
  - "**/tests/"
  - "**/spec/"
  - "**/__tests__/"
  - "**/vendor/"
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/*.test.jsx"
  - "**/*.spec.jsx"